server:
  port: 8080
spring:
  application:
    name: accounts
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3309/accountsdb
    username: root
    password: root
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
